/*
 * Umbra's payload -- the half no build outside the Dogwood repository had ever produced.
 *
 * `tools/standalone-check` proved a product could consume the generator and the host runtime; the
 * audit (`plans/adoption-audit.md` A2) observed that the *guest* toolchain -- `dogwood-compose`
 * from a repository, generated guest stubs, the Zipline plugin, signing -- had never been
 * assembled anywhere a path dependency could not paper over a packaging hole. This module is that
 * assembly. If it builds and `:app` renders it, the whole adoption path exists.
 */
plugins {
  kotlin("multiplatform")
  kotlin("plugin.serialization")
  id("org.jetbrains.kotlin.plugin.compose")
  id("app.cash.zipline")
}

kotlin {
  jvmToolchain(21)
  js(IR) {
    browser()
    binaries.executable()
  }
  sourceSets {
    jsMain {
      dependencies {
        // The guest runtime, from a repository. This line is most of what A2 tests: the published
        // JavaScript artifact carries the generated design-system stubs compiled in, and its
        // module name survived publication (the `outputModuleName` defect was found on the host
        // side of exactly this seam).
        implementation("dev.dogwood:dogwood-compose:0.1.0")
      }
      // Umbra's OWN components, generated by the Dogwood plugin in `:design` from Umbra's surface.
      // A source directory rather than a dependency, because the stubs are half of `:design`'s
      // boundary and have no artifact of their own -- the same arrangement `slice-screens` uses.
      kotlin.srcDir(project(":design").layout.buildDirectory.dir("generated/dogwood/umbraDesignSystem/guest"))
      // The screens, shared with `:web-guest`: one set of screens, two transports.
      kotlin.srcDir("screens/kotlin")
    }
  }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
  dependsOn(":design:generateUmbraDesignSystem")
}

/*
 * A THROWAWAY DEVELOPMENT KEY, committed on purpose so this sample builds for anyone who clones
 * it. It is the same well-known throwaway pair the Dogwood samples use, which is what lets `:app`
 * trust `DogwoodTrust.DEVELOPMENT_KEYS` from the published artifact instead of carrying a copy of
 * a public key. It signs nothing anyone should trust; a real signing key never lives in a
 * repository -- pass `-PumbraSigningKey=<hex>` or set it in `~/.gradle/gradle.properties`.
 */
val developmentSigningKey = "0ca845610dac5a568230ae0b4468004a787b5a541603554a0d3903535dd1f742"

zipline {
  mainFunction.set("dev.umbra.guest.main")
  optimizeForSmallArtifactSize()
  version.set("1.0.0")
  signingKeys {
    create("dogwood-development") {
      privateKeyHex.set(
        providers.gradleProperty("umbraSigningKey").getOrElse(developmentSigningKey),
      )
      algorithmId.set(app.cash.zipline.loader.SignatureAlgorithmId.Ed25519)
    }
  }
}
