/*
 * Project Dogwood -- the guest's wire encoder.
 *
 * The positional encoding of ADR-007, built as native JavaScript values and handed to
 * QuickJS's own `JSON.stringify`.
 *
 * The construction matters as much as the shape, and it is the reason this file is hand-written
 * rather than generated by `kotlinx.serialization`. Measured on the reference screen's initial
 * batch: this path costs 1.14 ms where routing the same data through `kotlinx.serialization`
 * costs 24 ms, because the serializer walk runs as interpreted bytecode inside QuickJS while
 * `JSON.stringify` is the interpreter's own C. Do not "clean this up" into a `@Serializable`
 * class; that change costs twenty times the frame budget.
 */
package dev.dogwood.compose

import dev.dogwood.protocol.Change
import dev.dogwood.protocol.ChangeBatch
import dev.dogwood.protocol.ChildAdd
import dev.dogwood.protocol.ChildMove
import dev.dogwood.protocol.ChildRemove
import dev.dogwood.protocol.Create
import dev.dogwood.protocol.ModifierElem
import dev.dogwood.protocol.ModifierSet
import dev.dogwood.protocol.PropertySet
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonPrimitive

internal const val K_CREATE = 0
internal const val K_PROPERTY = 1
internal const val K_MODIFIER = 2
internal const val K_CHILD_ADD = 3
internal const val K_CHILD_REMOVE = 4
internal const val K_CHILD_MOVE = 5

/** Converts a serialized value into a native JavaScript value `JSON.stringify` can walk. */
private fun nativeValue(value: JsonElement): Any? = when (value) {
  is JsonNull -> null
  is JsonPrimitive -> if (value.isString) value.content else value.content.toDoubleOrNull() ?: value.content
  // Structured values arrive only with deferred expressions, which do not exist yet. When they
  // do they need a positional shape of their own; ADR-007 does not define one.
  else -> value.toString()
}

private fun chain(elements: List<ModifierElem>): Array<Any?> =
  Array(elements.size) { arrayOf(elements[it].t.value, nativeValue(elements[it].v)) }

private fun change(c: Change): Array<Any?> = when (c) {
  is Create -> arrayOf(K_CREATE, c.i.value, c.w.value)
  is PropertySet -> arrayOf(K_PROPERTY, c.i.value, c.p.value, nativeValue(c.v))
  is ModifierSet -> arrayOf(K_MODIFIER, c.i.value, chain(c.e))
  is ChildAdd -> arrayOf(K_CHILD_ADD, c.i.value, c.s.value, c.c.value, c.x)
  is ChildRemove -> arrayOf(K_CHILD_REMOVE, c.i.value, c.s.value, c.x, c.n)
  is ChildMove -> arrayOf(K_CHILD_MOVE, c.i.value, c.s.value, c.f, c.t, c.n)
}

/** `[sequence, [change, ...]]`, per ADR-007 section 2.1. */
fun encodeBatch(batch: ChangeBatch): String {
  val changes = Array<Any?>(batch.g.size) { change(batch.g[it]) }
  return JSON.stringify(arrayOf<Any?>(batch.q, changes))
}
