/*
 * Project Dogwood -- the guest's wire encoder.
 *
 * The positional encoding of ADR-007, built as native JavaScript values and handed to
 * QuickJS's own `JSON.stringify`.
 *
 * The construction matters as much as the shape, and it is the reason this file is hand-written
 * rather than generated by `kotlinx.serialization`. Measured on the reference screen's initial
 * batch: this path costs 1.14 ms where routing the same data through `kotlinx.serialization`
 * costs 24 ms, because the serializer walk runs as interpreted bytecode inside QuickJS while
 * `JSON.stringify` is the interpreter's own C. Do not "clean this up" into a `@Serializable`
 * class; that change costs twenty times the frame budget.
 */
package dev.dogwood.compose

import dev.dogwood.protocol.Change
import dev.dogwood.protocol.ChangeBatch
import dev.dogwood.protocol.ChildAdd
import dev.dogwood.protocol.ChildMove
import dev.dogwood.protocol.ChildRemove
import dev.dogwood.protocol.Create
import dev.dogwood.protocol.ModifierElem
import dev.dogwood.protocol.ModifierSet
import dev.dogwood.protocol.PropertySet
import dev.dogwood.protocol.ChangeKind
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonPrimitive


/**
 * Converts a serialized value into a native JavaScript value `JSON.stringify` can walk.
 *
 * Booleans need naming explicitly. Without the two cases below they fall through to the numeric
 * branch, fail to parse as a number, and cross as the JSON *strings* `"true"` and `"false"`.
 * That went unnoticed on device because the host's reader parses either -- a leniency that hides
 * the bug rather than excusing it, since it costs two bytes per boolean and loses the type.
 */
private fun nativeValue(value: JsonElement): Any? = when (value) {
  is JsonNull -> null
  is JsonPrimitive -> when {
    value.isString -> value.content
    value.content == "true" -> true
    value.content == "false" -> false
    else -> value.content.toDoubleOrNull() ?: value.content
  }
  // Structured values: deferred expressions are arrays, `[factory, arg, ...]`. Before the
  // expression grammar existed this branch stringified them, which produced valid JSON carrying
  // the *text* of a recipe instead of the recipe -- the kind of bug that survives because the
  // output still parses.
  is JsonArray -> Array<Any?>(value.size) { nativeValue(value[it]) }
  is JsonObject -> {
    val target: dynamic = js("({})")
    for ((key, element) in value) target[key] = nativeValue(element)
    target
  }
}

private fun chain(elements: List<ModifierElem>): Array<Any?> =
  Array(elements.size) { arrayOf(elements[it].t.value, nativeValue(elements[it].v)) }

private fun change(c: Change): Array<Any?> = when (c) {
  is Create -> arrayOf(ChangeKind.CREATE, c.i.value, c.w.value)
  is PropertySet -> arrayOf(ChangeKind.PROPERTY, c.i.value, c.p.value, nativeValue(c.v))
  is ModifierSet -> arrayOf(ChangeKind.MODIFIER, c.i.value, chain(c.e))
  is ChildAdd -> arrayOf(ChangeKind.CHILD_ADD, c.i.value, c.s.value, c.c.value, c.x)
  is ChildRemove -> arrayOf(ChangeKind.CHILD_REMOVE, c.i.value, c.s.value, c.x, c.n)
  is ChildMove -> arrayOf(ChangeKind.CHILD_MOVE, c.i.value, c.s.value, c.f, c.t, c.n)
}

/** `[sequence, [change, ...]]`, per ADR-007 section 2.1. */
fun encodeBatch(batch: ChangeBatch): String {
  val changes = Array<Any?>(batch.g.size) { change(batch.g[it]) }
  return JSON.stringify(arrayOf<Any?>(batch.q, changes))
}
