/*
 * Project Dogwood -- the API reference, emitted from the same parse as everything else.
 *
 * `plans/production-readiness.md` lists four documents a product needs and says of this one: *the
 * guest surface is generated, so this is generated too, and nothing generates it.* This is the
 * missing half. It is deliberately not a hand-written page about the components -- a hand-written
 * page is a fifth thing that can disagree with the surface, and this repository has fixed that
 * class of drift three times.
 *
 * **What it can say and what it cannot.** It renders the parsed model: names, types, kinds, tags,
 * defaults, affordances and declared ranges. That is the whole of what a guest author needs in
 * order to *call* a component correctly and the whole of what an operator needs in order to read a
 * skew report. It carries no prose about what a component is *for*, because the parser does not
 * read documentation comments -- and a generator that invented that prose would be worse than one
 * that omits it.
 */
package dev.dogwood.codegen

/**
 * Renders one segment's reference as Markdown.
 *
 * @param dictionary the tags, which are the half a reader cannot work out from the surface source.
 * @param components the parse, which carries kinds, defaults and the markings.
 */
fun emitDocs(dictionary: Dictionary, components: List<ParsedComponent>): String = buildString {
  val byName = components.associateBy { it.name }

  appendLine("<!-- GENERATED by dogwood-codegen from the component surface. Do not edit. -->")
  appendLine("<!-- Regenerate with the segment's own generate task; see the module's build file. -->")
  appendLine()
  appendLine("# `${dictionary.wireName}` — component reference")
  appendLine()
  appendLine("Generated from the component surface, so it cannot disagree with what the generator")
  appendLine("actually emitted. Version **${dictionary.version}**, segment **${dictionary.segmentId}**.")
  appendLine()
  appendLine("A guest calls these as ordinary Kotlin Compose functions. Everything below describes")
  appendLine("how each one crosses the boundary.")
  appendLine()

  appendLine("## Reading this")
  appendLine()
  appendLine("| Column | What it means |")
  appendLine("| --- | --- |")
  appendLine("| **Tag** | the number on the wire. Widget tags are `(segment shl 24) or local`, so this segment's are `${dictionary.segmentId} shl 24` plus the local tag — which is how a number in a skew report becomes a name |")
  appendLine("| **Kind** | how the parameter crosses: a property, a content slot, an event, or a live-state holder the host owns |")
  appendLine("| **Default** | `host` means the guest sends nothing and the client picks. Absence is the sentinel, everywhere |")
  appendLine()
  appendLine("Two rules govern every number here, and both are enforced by the lock beside the surface:")
  appendLine()
  appendLine("- **Tags are permanent and append-only.** A renumbered tag does not fail to render; it")
  appendLine("  renders the *wrong widget* on a client one version behind.")
  appendLine("- **A parameter this client cannot read is not always harmless.** One marked")
  appendLine("  **affordance** governs what the user is allowed to do — `enabled`, `checked`,")
  appendLine("  `readOnly` — so a client meeting an unreadable one **withholds the whole widget**")
  appendLine("  rather than drawing a control that lies about what it will do. Every other kind of")
  appendLine("  skew degrades cosmetically. The components that own one are marked below.")
  appendLine()

  if (dictionary.reservedLocalTags.isNotEmpty()) {
    appendLine("**Reserved local tags: ${dictionary.reservedLocalTags.joinToString(", ")}.** Those")
    appendLine("belong to hand-written bindings in this same segment, not to the generator. They")
    appendLine("appear in no table below and are not free.")
    appendLine()
  }

  if (dictionary.enums.isNotEmpty()) {
    appendLine("## Enumerations")
    appendLine()
    appendLine("An entry crosses as its **name**. A client that meets a name it does not know renders the")
    appendLine("parameter's default and reports the name as skew, so adding an entry is a compatibility event")
    appendLine("and the lock requires the segment version to move with it. Entries are append-only.")
    appendLine()
    appendLine("| Enumeration | Entries |")
    appendLine("| --- | --- |")
    for ((name, entries) in dictionary.enums) {
      appendLine("| `$name` | ${entries.joinToString(", ") { "`$it`" }} |")
    }
    appendLine()
  }

  appendLine("## Components")
  appendLine()
  appendLine("| Component | Local tag | Widget tag | Owns an affordance |")
  appendLine("| --- | ---: | ---: | :---: |")
  for (entry in dictionary.components) {
    val tag = (dictionary.segmentId shl 24) or entry.localTag
    val affordance = if (entry.safetyRelevant.isEmpty()) "" else "yes"
    appendLine("| [`${entry.name}`](#${entry.name.lowercase()}) | ${entry.localTag} | $tag | $affordance |")
  }
  appendLine()

  for (entry in dictionary.components) {
    val component = byName[entry.name] ?: continue
    val tag = (dictionary.segmentId shl 24) or entry.localTag
    appendLine("---")
    appendLine()
    appendLine("### ${entry.name}")
    appendLine()
    appendLine("Local tag ${entry.localTag}, widget tag `$tag`.")
    appendLine()

    if (!component.isBindable) {
      appendLine("**Not bound.** The generator rejected this component, so no client renders it:")
      appendLine()
      for (parameter in component.parameters.filter { it.kind == ParameterKind.UNSUPPORTED }) {
        appendLine("- `${parameter.name}: ${parameter.type}` — ${parameter.rejection}")
      }
      appendLine()
      continue
    }

    val properties = component.wireProperties
    if (properties.isNotEmpty()) {
      appendLine("**Properties**")
      appendLine()
      appendLine("| Name | Type | Tag | Default | Notes |")
      appendLine("| --- | --- | ---: | --- | --- |")
      for ((index, property) in properties.withIndex()) {
        val parameter = property.parameter
        val notes = buildList {
          if (parameter.affordance) add("**affordance**")
          parameter.range?.let { add("range ${trim(it.min)}..${trim(it.max)}, clamped") }
          property.holder?.let { add("from the `${parameter.name}` holder (`${it.field}`)") }
          if (parameter.kind == ParameterKind.HOST_RESOLVED) add("resolved by the host at draw time")
          parameter.enumType?.let { add("one of ${it.entries.joinToString(", ") { e -> "`$e`" }}, by name") }
        }.joinToString("; ")
        // A holder's properties are not the parameter's: the parameter is the holder object and
        // may be absent, while these carry the holder's own fields. Showing the parameter's
        // default here would say `null` for six properties whose wire absence means something
        // else entirely -- "nobody is driving this".
        val default = property.holder?.let { "`${it.absent}` when absent" } ?: describeDefault(parameter)
        appendLine(
          "| `${property.name}` | `${property.type}` | ${index + 1} | $default | $notes |",
        )
      }
      appendLine()
    }

    val slots = component.slots
    if (slots.isNotEmpty()) {
      appendLine("**Content slots**")
      appendLine()
      appendLine("| Name | Tag |")
      appendLine("| --- | ---: |")
      for ((index, slot) in slots.withIndex()) appendLine("| `${slot.name}` | ${index + 1} |")
      appendLine()
    }

    val events = component.wireEvents
    if (events.isNotEmpty()) {
      appendLine("**Events**")
      appendLine()
      appendLine("| Name | Signature | Tag | Notes |")
      appendLine("| --- | --- | ---: | --- |")
      for ((index, event) in events.withIndex()) {
        val note = if (event.report != null) {
          "the host's report back into the `${event.parameter.name}` holder"
        } else {
          ""
        }
        appendLine("| `${event.name}` | `${event.type}` | ${index + 1} | $note |")
      }
      appendLine()
    }

    if (component.modifier != null) {
      appendLine("Takes a modifier chain.")
      appendLine()
    }

    if (entry.safetyRelevant.isNotEmpty()) {
      appendLine(
        "**Owns an affordance** (${entry.safetyRelevant.sorted().joinToString(", ") { "`$it`" }}), " +
          "so a client that meets a property it cannot read on this component withholds it entirely.",
      )
      appendLine()
    }
  }
}

/** `1.0` rather than `1.0000000` for a bound written as an integer on the surface. */
private fun trim(value: Double): String =
  if (value == value.toLong().toDouble()) value.toLong().toString() else value.toString()

private fun describeDefault(parameter: ParsedParameter): String = when {
  !parameter.hasDefault -> "required"
  parameter.defaultIsHostResolved -> "host"
  else -> "`${parameter.defaultExpression}`"
}
