/*
 * Project Dogwood -- the emitters.
 *
 * Four artifacts from one parsed model. Two are here; the value-type stand-ins and the host
 * bindings share the same shape and are noted where they are not yet built.
 *
 * Tag assignment is the load-bearing part. Tags are assigned by declaration order and never
 * renumbered, because the protocol's evolution rule is additive: a component that gains an
 * optional parameter appends a tag, and a client one dictionary version behind keeps rendering
 * everything it already knew. Sorting the components, or numbering by anything derived from the
 * signature, would silently re-map tags on an unrelated edit.
 */
package dev.dogwood.codegen

import kotlinx.serialization.json.Json

private val json = Json { prettyPrint = true }

/** Where the guest runtime the stubs are built from actually lives. */
private const val GUEST_RUNTIME_PACKAGE = "dev.dogwood.compose"

/** Where the host runtime the bindings are built from actually lives. */
private const val HOST_RUNTIME_PACKAGE = "dev.dogwood.host"

/**
 * Builds the dictionary. Declaration order in, stable tags out.
 *
 * @param reservedLocalTags tags in this segment that hand-written bindings already answer to. The
 *   generator allocates around them; see [Dictionary.reservedLocalTags] for why that is not
 *   optional.
 */
fun buildDictionary(
  segmentName: String,
  segmentId: Int,
  version: Int,
  components: List<ParsedComponent>,
  reservedLocalTags: Set<Int> = emptySet(),
  wireName: String = segmentName,
): Dictionary {
  val allocated = ArrayList<Int>(components.size)
  var next = 1
  repeat(components.size) {
    while (next in reservedLocalTags) next++
    allocated += next
    next++
  }
  return Dictionary(
  segmentName = segmentName,
  wireName = wireName,
  segmentId = segmentId,
  version = version,
  reservedLocalTags = reservedLocalTags.sorted(),
  components = components.mapIndexed { index, component ->
    DictionaryEntry(
      name = component.name,
      localTag = allocated[index],
      // Holders expand here, in declaration order with everything else, so appending a holder to
      // a surface appends tags rather than renumbering the properties around it.
      properties = component.wireProperties.mapIndexed { i, p -> p.name to i + 1 }.toMap(),
      propertyTypes = component.wireProperties.associate { it.name to it.type },
      safetyRelevant = component.affordances.mapTo(mutableSetOf()) { it.name },
      slots = component.slots.mapIndexed { i, p -> p.name to i + 1 }.toMap(),
      events = component.wireEvents.mapIndexed { i, p -> p.name to i + 1 }.toMap(),
      eventTypes = component.wireEvents.associate { it.name to it.type },
      rejected = component.parameters
        .filter { it.kind == ParameterKind.UNSUPPORTED }
        .associate { it.name to (it.rejection ?: "unsupported") },
    )
  },
  )
}

fun Dictionary.encode(): String = json.encodeToString(Dictionary.serializer(), this)

/**
 * Emits the guest stubs.
 *
 * Note what the emitted code does *not* do for a parameter whose default the host must resolve:
 * it does not send one. Absence is the "use host default" sentinel, and it is the only correct
 * encoding for a default the guest cannot evaluate — a `@Composable` default has no value until
 * it is composed, on the host, in context. Emitting a guest-computed stand-in would be a silent
 * theming bug on every screen.
 */
fun emitGuestStubs(packageName: String, dictionary: Dictionary, components: List<ParsedComponent>): String =
  buildString {
    appendLine("// Generated by dogwood-codegen. Do not edit.")
    appendLine("//")
    appendLine("// Segment '${dictionary.segmentName}' (id ${dictionary.segmentId}), version ${dictionary.version}.")
    // Generated stubs are the intended caller of the guest runtime's recording seam, and the only
    // one; `@DogwoodGeneratedApi` says so at every other call site. See `GeneratedApi.kt`.
    appendLine("@file:OptIn($GUEST_RUNTIME_PACKAGE.DogwoodGeneratedApi::class)")
    appendLine()
    appendLine("package $packageName")
    appendLine()
    // A product's stubs live in the product's package, and everything they are built from --
    // `ComposeNode`'s applier, `newWidget`, `recording`, `Children`, `Modifier`, `TextValue` --
    // lives in Dogwood's. Emitted only when they differ: importing your own package is legal and
    // pointless, and the generated file for Dogwood's own segment should not carry a line whose
    // only purpose is to be a no-op.
    if (packageName != GUEST_RUNTIME_PACKAGE) appendLine("import $GUEST_RUNTIME_PACKAGE.*")
    appendLine("import androidx.compose.runtime.Composable")
    appendLine("import androidx.compose.runtime.ComposeNode")
    appendLine("import dev.dogwood.protocol.ChildrenTag")
    appendLine("import dev.dogwood.protocol.EventTag")
    appendLine("import dev.dogwood.protocol.PropertyTag")
    appendLine("import dev.dogwood.protocol.widgetTag")
    appendLine("import kotlinx.serialization.json.JsonPrimitive")
    appendLine("import kotlinx.serialization.json.booleanOrNull")
    appendLine("import kotlinx.serialization.json.floatOrNull")
    appendLine("import kotlinx.serialization.json.intOrNull")
    appendLine("import kotlinx.serialization.json.jsonPrimitive")
    appendLine()

    for (component in components.filter { it.isBindable }) {
      val entry = dictionary.components.first { it.name == component.name }
      appendLine("@Composable")
      append("fun ${component.name}(")
      appendLine()
      for (parameter in component.parameters) {
        val default = when {
          parameter.kind == ParameterKind.MODIFIER -> " = Modifier"
          parameter.defaultIsHostResolved -> " = null"
          parameter.hasDefault -> " = ${parameter.defaultExpression}"
          else -> ""
        }
        val type = if (parameter.defaultIsHostResolved && !parameter.type.endsWith("?")) {
          "${parameter.type}?"
        } else {
          parameter.type
        }
        appendLine("  ${parameter.name}: $type$default,")
      }
      appendLine(") {")
      // A holder's fields are read **here**, in the composable body, and not inside `update`.
      // That is what subscribes this call site to the holder's snapshot state; a read inside
      // `update` happens after the composition has already decided not to recompose, so a target
      // declared between frames would never cross. `LazyListState`'s hand-written container
      // carries the same comment, and it is the one thing about this pattern that is easy to get
      // wrong and invisible when you do.
      for (parameter in component.holders) {
        val shape = parameter.holderShape!!
        for (property in shape.properties) {
          // Nullable, and left null when the guest passed no holder. Absence is the sentinel
          // everywhere else in this protocol and it has to be here too: a stub that sent a
          // holder's properties unconditionally would put two tags on every one of these widgets,
          // and a client one dictionary version behind meets two property tags it has never seen
          // on a widget that owns an affordance -- which is defined to withhold it. Every text
          // field on that client would go blank because a *newer* guest declined to ask for focus.
          appendLine("  val ${parameter.name}${property.suffix} = ${parameter.name}?.${property.field}")
        }
      }
      appendLine("  ComposeNode<WidgetNode, DogwoodApplier>(")
      appendLine("    factory = { newWidget(widgetTag(${dictionary.segmentId}, ${entry.localTag})) },")
      appendLine("    update = {")
      for (parameter in component.holders) {
        val shape = parameter.holderShape!!
        for (property in shape.properties) {
          val local = "${parameter.name}${property.suffix}"
          appendLine("      set($local) { if (it != null) recording.recorder.property(id, PropertyTag(${entry.properties.getValue(local)}), JsonPrimitive(it)) }")
        }
        val report = shape.report ?: continue
        val tag = entry.events.getValue("${parameter.name}Report")
        // Keyed on the holder itself, so passing null clears the slot. Registering nothing is not
        // the same as registering a no-op: a report handler from a previous composition would keep
        // feeding a holder the guest has stopped using.
        appendLine("      set(${parameter.name}) { holder ->")
        appendLine("        if (holder == null) {")
        appendLine("          recording.lambdas.clear(id, EventTag($tag))")
        appendLine("        } else {")
        appendLine("          recording.lambdas.set(id, EventTag($tag)) { args ->")
        appendLine("            holder.${report.method}(")
        report.arguments.forEachIndexed { index, argument ->
          appendLine("              ${argument.name} = ${decodeArgument(argument.type, index, argument.absent)},")
        }
        appendLine("            )")
        appendLine("          }")
        appendLine("        }")
        appendLine("      }")
      }
      for (parameter in component.values) {
        val tag = entry.properties.getValue(parameter.name)
        // A host-resolved value already carries its own wire form -- a literal or a recipe -- so
        // it is written straight through. Wrapping it in `JsonPrimitive` would not compile, which
        // is how this gap was found: the parameter kind existed and nothing emitted for it.
        val encode = if (parameter.kind == ParameterKind.HOST_RESOLVED) "it.json" else "JsonPrimitive(it)"
        if (parameter.defaultIsHostResolved || parameter.type.endsWith("?")) {
          // Absence is the sentinel: an unset optional parameter sends nothing at all, and the
          // host resolves its own default. Sending an explicit null instead would put the word
          // "null" on the wire and, given a careless reader, on the screen.
          appendLine("      set(${parameter.name}) { if (it != null) recording.recorder.property(id, PropertyTag($tag), $encode) }")
        } else {
          appendLine("      set(${parameter.name}) { recording.recorder.property(id, PropertyTag($tag), $encode) }")
        }
      }
      component.modifier?.let {
        appendLine("      set(${it.name}) { if (it.elements.isNotEmpty()) recording.recorder.modifiers(id, it.elements) }")
        // `reconcile`, not `set`: it runs on every update rather than only when the chain
        // changes. A completion callback captured where the chain last *changed* would go stale,
        // which is the same defect the viewport reporter had.
        appendLine("      reconcile { applyModifier(id, ${it.name}) }")
      }
      for (parameter in component.events) {
        val tag = entry.events.getValue(parameter.name)
        if (parameter.type.trim().endsWith("?")) {
          // An optional callback. Registering nothing is not the same as registering a no-op: the
          // slot has to be *cleared*, or a handler from a previous composition keeps receiving
          // events after the guest has stopped asking for them.
          appendLine("      set(${parameter.name}) { handler ->")
          appendLine("        if (handler == null) {")
          appendLine("          recording.lambdas.clear(id, EventTag($tag))")
          appendLine("        } else {")
          appendLine("          recording.lambdas.set(id, EventTag($tag)) ${guestEventBody(parameter)}")
          appendLine("        }")
          appendLine("      }")
        } else {
          appendLine("      set(${parameter.name}) { handler -> recording.lambdas.set(id, EventTag($tag)) ${guestEventBody(parameter)} }")
        }
      }
      appendLine("    },")
      if (component.slots.isNotEmpty()) {
        val slot = component.slots.first()
        val tag = entry.slots.getValue(slot.name)
        appendLine("    content = { Children(ChildrenTag($tag), ${slot.name}) },")
      }
      appendLine("  )")
      appendLine("}")
      appendLine()

      // A convenience overload with every `TextValue` parameter as a plain `String`, so that
      // widening a parameter's type does not break every existing call site for no benefit --
      // most text really is a literal. Two overloads, never a combinatorial set: a call that mixes
      // a literal and a recipe writes `TextValue("...")` for the literal half.
      //
      // **Emitted only when at least one text parameter is required**, and that condition is not a
      // nicety. Two overloads whose parameters all have defaults are both applicable to a call
      // that omits them, and Kotlin rejects it as ambiguous -- so a component whose text is
      // entirely optional would become *harder* to call than before, at every call site, including
      // the ones passing no text at all. A required text parameter is what tells the two apart:
      // supply it as a `String` and only this overload matches; supply a `TextValue` or omit
      // nothing and only the primary one does.
      val textParameters = component.parameters.filter {
        it.kind == ParameterKind.HOST_RESOLVED && it.type.removeSuffix("?") == "TextValue"
      }
      val hasRequiredText = textParameters.any { !it.type.endsWith("?") && !it.hasDefault }
      if (textParameters.isNotEmpty() && hasRequiredText) {
        appendLine("/** Convenience overload: every text parameter as a plain literal. */")
        appendLine("@Composable")
        appendLine("fun ${component.name}(")
        for (parameter in component.parameters) {
          val isText = parameter in textParameters
          val type = when {
            isText && parameter.type.endsWith("?") -> "String?"
            isText -> "String"
            parameter.kind == ParameterKind.MODIFIER -> "Modifier"
            parameter.defaultIsHostResolved && !parameter.type.endsWith("?") -> "${parameter.type}?"
            else -> parameter.type
          }
          val default = when {
            parameter.kind == ParameterKind.MODIFIER -> " = Modifier"
            parameter.defaultIsHostResolved -> " = null"
            parameter.hasDefault -> " = ${parameter.defaultExpression}"
            else -> ""
          }
          appendLine("  ${parameter.name}: $type$default,")
        }
        appendLine(") {")
        appendLine("  ${component.name}(")
        for (parameter in component.parameters) {
          val argument = when {
            parameter !in textParameters -> parameter.name
            parameter.type.endsWith("?") -> "${parameter.name}?.let(::TextValue)"
            else -> "TextValue(${parameter.name})"
          }
          appendLine("    ${parameter.name} = $argument,")
        }
        appendLine("  )")
        appendLine("}")
        appendLine()
      }
    }
  }

/** A human-readable report of what the rule declined to bind, and why. */
fun emitAuditReport(components: List<ParsedComponent>): String = buildString {
  appendLine("| Component | Verdict | Reason |")
  appendLine("| --- | --- | --- |")
  for (component in components) {
    if (component.isBindable) {
      appendLine("| `${component.name}` | bindable | — |")
    } else {
      val reasons = component.parameters
        .filter { it.kind == ParameterKind.UNSUPPORTED }
        .joinToString("; ") { "`${it.name}`: ${it.rejection}" }
      appendLine("| `${component.name}` | **rejected** | $reasons |")
    }
  }
}

/**
 * Emits the host binding layer.
 *
 * The generator emits the **bridge**, not the widget. A binding unpacks a node's properties,
 * slots and events and calls an implementation a human wrote; it does not decide what a badge
 * looks like. That split is the whole architecture: the part that grows without bound as a design
 * system grows is generated, and the part that requires taste is not.
 *
 * Redwood draws the same line, and it is why "the registry stops being a treadmill; it does not
 * stop existing".
 */
fun emitHostBindings(
  packageName: String,
  implementationPackage: String,
  dictionary: Dictionary,
  components: List<ParsedComponent>,
): String = buildString {
  val bindable = components.filter { it.isBindable }
  appendLine("// Generated by dogwood-codegen. Do not edit.")
  appendLine("//")
  appendLine("// Segment '${dictionary.segmentName}' (id ${dictionary.segmentId}), version ${dictionary.version}.")
  appendLine("package $packageName")
  appendLine()
  // As above, for the host half: `WidgetView`, `LayoutScope`, `EventSink`, `RenderChildren`, the
  // property readers and `DogwoodSegmentBinding` are all Dogwood's.
  if (packageName != HOST_RUNTIME_PACKAGE) appendLine("import $HOST_RUNTIME_PACKAGE.*")
  appendLine("import androidx.compose.runtime.Composable")
  appendLine("import dev.dogwood.protocol.EventTag")
  appendLine("import dev.dogwood.protocol.widgetTag")
  appendLine("import kotlinx.serialization.json.JsonPrimitive")
  appendLine()
  appendLine("/**")
  appendLine(" * The version this client advertises for this segment, so a guest can branch on what")
  appendLine(" * this client is capable of.")
  appendLine(" *")
  appendLine(" * Emitted rather than hand-written. It was hand-written, in `Bindings.kt`, and it")
  appendLine(" * drifted the first time the lock raised the version: the dictionary said one number")
  appendLine(" * and the number handed to guests said another, which is exactly the failure the")
  appendLine(" * version exists to prevent.")
  appendLine(" */")
  appendLine("const val ${dictionary.segmentName.replaceFirstChar { it.uppercase() }}Version: Int = ${dictionary.version}")
  appendLine()
  appendLine("/** Local tags this segment binds, for the dictionary check and for skew reporting. */")
  appendLine("val ${dictionary.segmentName.replaceFirstChar { it.uppercase() }}Tags: Set<Int> = setOf(")
  for (entry in dictionary.components.filter { e -> bindable.any { it.name == e.name } }) {
    appendLine("  widgetTag(${dictionary.segmentId}, ${entry.localTag}).value,")
  }
  appendLine(")")
  appendLine()
  appendLine("/**")
  appendLine(" * What each of those tags is called.")
  appendLine(" *")
  appendLine(" * Emitted for skew telemetry, and it is not cosmetic there. A withheld widget is the")
  appendLine(" * most serious entry a skew report carries -- this client refused to draw a control")
  appendLine(" * because a payload said something about it that could not be read -- and reporting it")
  appendLine(" * as `Widget#16777217` makes the one row a team must act on the one row nobody can.")
  appendLine(" */")
  appendLine("val ${dictionary.segmentName.replaceFirstChar { it.uppercase() }}Names: Map<Int, String> = mapOf(")
  for (entry in dictionary.components.filter { e -> bindable.any { it.name == e.name } }) {
    appendLine("  widgetTag(${dictionary.segmentId}, ${entry.localTag}).value to \"${entry.name}\",")
  }
  appendLine(")")
  appendLine()
  appendLine("/**")
  appendLine(" * Dispatches one node to its implementation. Returns false when the tag is not ours,")
  appendLine(" * so a caller can try another segment before falling back to a placeholder.")
  appendLine(" *")
  appendLine(" * The tag is checked **before** the modifier chain is built, and that ordering is")
  appendLine(" * load-bearing rather than tidy. Building it first meant every node from another")
  appendLine(" * segment built its chain twice -- once here, once in the caller after this returned")
  appendLine(" * false. That was merely wasteful until modifier arguments could be animated, at which")
  appendLine(" * point it became two animations and two completion events for one declared target.")
  appendLine(" */")
  appendLine("@Composable")
  appendLine("fun bind${dictionary.segmentName.replaceFirstChar { it.uppercase() }}(")
  appendLine("  node: WidgetView,")
  appendLine("  scope: LayoutScope,")
  appendLine("  events: EventSink,")
  appendLine("): Boolean {")
  appendLine("  if (node.tag.value !in ${dictionary.segmentName.replaceFirstChar { it.uppercase() }}Tags) return false")
  appendLine("  val modifier = node.composeModifier(scope, events)")
  appendLine("  if (withholdUnsafe(node, modifier)) return true")
  appendLine("  when (node.tag.value) {")

  for (component in bindable) {
    val entry = dictionary.components.first { it.name == component.name }
    appendLine("    widgetTag(${dictionary.segmentId}, ${entry.localTag}).value ->")
    appendLine("      $implementationPackage.${component.name}Impl(")
    for (parameter in component.values) {
      val tag = entry.properties.getValue(parameter.name)
      appendLine("        ${parameter.name} = ${reader(parameter, tag, component.name)},")
    }
    for (parameter in component.holders) {
      val shape = parameter.holderShape!!
      // The generated binding builds the mirror and hands it over. What the mirror *does* is
      // hand-written, for the same reason the widget is: moving a list, taking focus or opening a
      // sheet is the part that requires taste, and it is not the part that grows without bound.
      // Named, not positional. A shape with five properties passed positionally is two `Int`
      // arguments away from a silent transposition -- the mirror compiles, the container scrolls
      // to the sequence number, and nothing says so.
      val arguments = shape.properties.joinToString(", ") { property ->
        val tag = entry.properties.getValue("${parameter.name}${property.suffix}")
        val read = when (property.type) {
          "Boolean" -> "node.boolean($tag, ${property.absent})"
          "Int" -> "node.int($tag, ${property.absent})"
          "Float" -> "node.float($tag, ${property.absent})"
          else -> "node.string($tag, ${property.absent})"
        }
        "${property.field} = $read"
      }
      val report = shape.report
      val reporting = if (report == null) "" else {
        val tag = entry.events.getValue("${parameter.name}Report")
        val names = report.arguments.indices.joinToString(", ") { "a$it" }
        val encoded = report.arguments.indices.joinToString(", ") { "JsonPrimitive(a$it)" }
        ", report = { $names -> events.send(node, EventTag($tag), listOf($encoded)) }"
      }
      appendLine("        ${parameter.name} = ${shape.mirror}($arguments$reporting),")
    }
    component.modifier?.let { appendLine("        ${it.name} = modifier,") }
    for (parameter in component.events) {
      val tag = entry.events.getValue(parameter.name)
      appendLine("        ${parameter.name} = ${eventLambda(parameter, tag)},")
    }
    for (parameter in component.slots) {
      val tag = entry.slots.getValue(parameter.name)
      appendLine("        ${parameter.name} = { RenderChildren(node, $tag, scope, events) },")
    }
    appendLine("      )")
  }

  appendLine("    else -> return false")
  appendLine("  }")
  appendLine("  return true")
  appendLine("}")
  appendLine()
  val prefix = dictionary.segmentName.replaceFirstChar { it.uppercase() }
  appendLine("/**")
  appendLine(" * This segment, as something a host can register.")
  appendLine(" *")
  appendLine(" * `RenderNode` dispatches through `DogwoodRegistry` rather than by naming a segment,")
  appendLine(" * so a product runs the generator over its own surface and registers what it emits.")
  appendLine(" * That is the whole of the registration mechanism -- the wire format, the skew rules,")
  appendLine(" * the affordance guard and the dictionary lock work on a product segment because they")
  appendLine(" * are the same code, not a second copy parameterised by segment.")
  appendLine(" */")
  appendLine("object ${prefix}Binding : DogwoodSegmentBinding {")
  appendLine("  override val segmentName: String = \"${dictionary.wireName}\"")
  appendLine("  override val segmentVersion: Int = ${prefix}Version")
  appendLine("  override val tags: Set<Int> = ${prefix}Tags")
  appendLine("  override val names: Map<Int, String> = ${prefix}Names")
  appendLine("  @Composable")
  appendLine("  override fun bind(node: WidgetView, scope: LayoutScope, events: EventSink): Boolean =")
  appendLine("    bind$prefix(node, scope, events)")
  appendLine("}")
  appendLine()
  emitWithholding(dictionary, bindable)
}

/**
 * Emits the affordance guard.
 *
 * Section 6 of the technical specification requires that a widget carrying a safety-relevant
 * parameter this client does not understand is **replaced by a declared fallback rather than
 * rendered wrong**. This is where that happens, and the shape follows from what a client can
 * actually observe.
 *
 * A client meeting a property tag it does not know cannot tell what that property meant: the tag
 * comes from a dictionary it has never seen. So it cannot ask "is this unknown property the one
 * that disables the button?" -- the decision has to be made per widget instead. A widget that owns
 * no affordance ignores unknown properties, because for it the worst case is cosmetic and
 * withholding the whole widget would be a far larger regression than the skew. A widget that owns
 * one refuses to draw, because the worst case is a control that lies about what it will do.
 *
 * The fallback is the same inert placeholder an unknown widget tag already produces. That is
 * deliberate: it keeps index arithmetic consistent, occupies the slot, and offers the user nothing
 * to act on -- which is the whole requirement.
 */
private fun StringBuilder.emitWithholding(
  dictionary: Dictionary,
  bindable: List<ParsedComponent>,
) {
  val guarded = bindable.filter { it.affordances.isNotEmpty() }
  val prefix = dictionary.segmentName.replaceFirstChar { it.uppercase() }

  appendLine("/**")
  appendLine(" * Widgets whose contract includes an affordance -- something the user is allowed to")
  appendLine(" * do -- mapped to the property tags this client understands for them.")
  appendLine(" *")
  appendLine(" * A widget absent from this map has no affordance to get wrong, and ignores unknown")
  appendLine(" * properties as ordinary cosmetic skew.")
  appendLine(" */")
  appendLine("private val ${prefix}Affordances: Map<Int, Set<Int>> = mapOf(")
  for (component in guarded) {
    val entry = dictionary.components.first { it.name == component.name }
    val known = entry.properties.values.sorted().joinToString(", ")
    val names = component.affordances.joinToString(", ") { it.name }
    appendLine("  // ${component.name}: $names")
    appendLine("  widgetTag(${dictionary.segmentId}, ${entry.localTag}).value to setOf($known),")
  }
  appendLine(")")
  appendLine()
  appendLine("/**")
  appendLine(" * Draws the fallback in place of a control this client cannot safely render.")
  appendLine(" *")
  appendLine(" * True when a widget that owns an affordance arrived carrying a property tag this")
  appendLine(" * client does not know -- which means a payload built against a newer dictionary is")
  appendLine(" * telling this client something about the control that it cannot read. Rendering")
  appendLine(" * anyway would show a control whose behaviour the payload was trying to change.")
  appendLine(" *")
  appendLine(" * It draws rather than merely refusing, and it draws with the guest's own modifier.")
  appendLine(" * Returning without composing anything would let the node vanish and everything")
  appendLine(" * after it move up, turning a contained safety problem into a visibly broken")
  appendLine(" * screen; keeping the modifier means the gap is the size the guest asked for.")
  appendLine(" */")
  appendLine("@Composable")
  appendLine("private fun withholdUnsafe(node: WidgetView, modifier: androidx.compose.ui.Modifier): Boolean {")
  appendLine("  val known = ${prefix}Affordances[node.tag.value] ?: return false")
  appendLine("  if (node.unknownProperties(known).isEmpty()) return false")
  appendLine("  LocalSkewReport.current.withheldWidgets += node.tag.value")
  appendLine("  androidx.compose.foundation.layout.Box(modifier)")
  appendLine("  return true")
  appendLine("}")
}

/**
 * The guest side of an event's arguments.
 *
 * The slot table stores a lambda taking the event's argument list, so a handler declared
 * `(Boolean) -> Unit` has to be called with that boolean decoded out of the list. Emitting
 * `{ handler() }` for every event compiles only for the zero-argument case, which is why the
 * first event with an argument found this.
 */
/**
 * The declared arguments of an event lambda.
 *
 * Reads them from the *normalized* type, so a nullable lambda's own wrapper is not mistaken for an
 * argument list. `(() -> Unit)?` takes nothing; read naively it appears to take one argument
 * called `) -> Unit`, and both ends of the boundary would have been generated to pass it.
 */
internal fun eventArguments(parameter: ParsedParameter): List<String> {
  var bare = parameter.type.trim()
  if (bare.endsWith("?")) bare = bare.dropLast(1).trim()
  if (bare.startsWith("((")) bare = bare.substring(1).trim()
  return bare.substringAfter("(").substringBefore(")")
    .split(",").map { it.trim() }.filter { it.isNotEmpty() }
}

/** Decodes one positional event argument on the guest side. */
private fun decodeArgument(type: String, index: Int, absent: String): String =
  when (type.removeSuffix("?")) {
    "Boolean" -> "args.getOrNull($index)?.jsonPrimitive?.booleanOrNull ?: $absent"
    "Int" -> "args.getOrNull($index)?.jsonPrimitive?.intOrNull ?: $absent"
    "Float" -> "args.getOrNull($index)?.jsonPrimitive?.floatOrNull ?: $absent"
    else -> "args.getOrNull($index)?.jsonPrimitive?.content ?: $absent"
  }

private fun guestEventBody(parameter: ParsedParameter): String {
  val arguments = eventArguments(parameter)
  if (arguments.isEmpty()) return "{ handler() }"
  val decoded = arguments.mapIndexed { index, type ->
    when (type.removeSuffix("?")) {
      "Boolean" -> "args[$index].jsonPrimitive.booleanOrNull ?: false"
      "Int" -> "args[$index].jsonPrimitive.intOrNull ?: 0"
      "Float" -> "args[$index].jsonPrimitive.floatOrNull ?: 0f"
      else -> "args[$index].jsonPrimitive.content"
    }
  }
  return "{ args -> handler(${decoded.joinToString(", ")}) }"
}

/**
 * The lambda a binding hands to an implementation.
 *
 * Its shape has to match the declared one: an event declared `(Boolean) -> Unit` must be handed a
 * one-argument lambda, and that argument has to reach the guest. `Event` has carried an argument
 * list since ADR-004's first draft, and this is where the generator uses it.
 */
private fun eventLambda(parameter: ParsedParameter, tag: Int): String {
  val arguments = eventArguments(parameter)
  if (arguments.isEmpty()) return "{ events.send(node, EventTag($tag)) }"
  val names = arguments.indices.map { "a$it" }
  val encoded = names.joinToString(", ") { "JsonPrimitive($it)" }
  return "{ ${names.joinToString(", ")} -> events.send(node, EventTag($tag), listOf($encoded)) }"
}

/**
 * How a binding reads one property.
 *
 * A host-resolved default is read as null and the implementation supplies its own, which is the
 * receiving half of absence-as-sentinel: the guest sent nothing precisely so the host could
 * decide, and a binding that substituted a value here would throw that away.
 */
private fun reader(parameter: ParsedParameter, tag: Int, owner: String): String {
  val nullable = parameter.defaultIsHostResolved || parameter.type.endsWith("?")
  if (parameter.kind == ParameterKind.HOST_RESOLVED) {
    // Resolved against the environment in force, which is why these readers are composable and
    // the primitive ones are not. The implementation still receives a plain platform type: the
    // part that requires taste never learns a recipe was involved.
    val fallback = parameter.defaultExpression?.takeIf { !parameter.defaultIsHostResolved }
    return when (parameter.type.removeSuffix("?")) {
      "TextValue" -> if (nullable) "node.textOrNull($tag)" else "node.text($tag, ${fallback ?: "\"\""})"
      "Color" -> if (nullable) "node.colorOrNull($tag)" else "node.color($tag, ${fallback ?: "palette().ink"})"
      "Shape" -> if (nullable) "node.shapeOrNull($tag)" else "node.shape($tag, ${fallback ?: "RectangleShape"})"
      else -> "node.property($tag)"
    }
  }
  // The surface's own default is carried through. Substituting a plausible-looking zero here
  // would make the generated binding disagree with the declaration it was generated from, which
  // is the one failure the whole approach is supposed to make impossible.
  val fallback = parameter.defaultExpression?.takeIf { !parameter.defaultIsHostResolved }
  val range = parameter.range
  return when (parameter.type.removeSuffix("?")) {
    "String" -> if (nullable) "node.stringOrNull($tag)" else "node.string($tag, ${fallback ?: "\"\""})"
    // A declared range emits a clamping reader. Nullable parameters are left alone deliberately:
    // absence is the "use host default" sentinel, and a clamp cannot improve on a value that is
    // not there. See `@Range` on the surface and ADR-035.
    "Int" -> when {
      nullable -> "node.intOrNull($tag)"
      range != null -> "node.intClamped($tag, ${fallback ?: "0"}, " +
        "min = ${range.min.toInt()}, max = ${clampedIntMax(range.max)}, " +
        "what = \"$owner.${parameter.name}\")"
      else -> "node.int($tag, ${fallback ?: "0"})"
    }
    "Float" -> when {
      nullable -> "node.floatOrNull($tag)"
      range != null -> "node.floatClamped($tag, ${fallback ?: "0f"}, " +
        "min = ${range.min}f, max = ${clampedFloatMax(range.max)}, " +
        "what = \"$owner.${parameter.name}\")"
      else -> "node.float($tag, ${fallback ?: "0f"})"
    }
    "Boolean" -> if (nullable) "node.booleanOrNull($tag)" else "node.boolean($tag, ${fallback ?: "false"})"
    else -> "node.property($tag)"
  }
}

/**
 * An unbounded `@Range` maximum reaches the emitter as `Double.MAX_VALUE`, which is not a legal
 * `Int` and would overflow to a negative one if narrowed by cast. Both of these emit the type's
 * own maximum instead, so "no upper bound" means what it says in the generated code.
 */
private fun clampedIntMax(max: Double): String =
  if (max >= Int.MAX_VALUE.toDouble()) "Int.MAX_VALUE" else max.toInt().toString()

private fun clampedFloatMax(max: Double): String =
  if (max >= Float.MAX_VALUE.toDouble()) "Float.MAX_VALUE" else "${max}f"
