/*
 * Project Dogwood -- the emitters.
 *
 * Four artifacts from one parsed model. Two are here; the value-type stand-ins and the host
 * bindings share the same shape and are noted where they are not yet built.
 *
 * Tag assignment is the load-bearing part. Tags are assigned by declaration order and never
 * renumbered, because the protocol's evolution rule is additive: a component that gains an
 * optional parameter appends a tag, and a client one dictionary version behind keeps rendering
 * everything it already knew. Sorting the components, or numbering by anything derived from the
 * signature, would silently re-map tags on an unrelated edit.
 */
package dev.dogwood.codegen

import kotlinx.serialization.json.Json

private val json = Json { prettyPrint = true }

/** Builds the dictionary. Declaration order in, stable tags out. */
fun buildDictionary(
  segmentName: String,
  segmentId: Int,
  version: Int,
  components: List<ParsedComponent>,
): Dictionary = Dictionary(
  segmentName = segmentName,
  segmentId = segmentId,
  version = version,
  components = components.mapIndexed { index, component ->
    DictionaryEntry(
      name = component.name,
      localTag = index + 1,
      properties = component.values.mapIndexed { i, p -> p.name to i + 1 }.toMap(),
      slots = component.slots.mapIndexed { i, p -> p.name to i + 1 }.toMap(),
      events = component.events.mapIndexed { i, p -> p.name to i + 1 }.toMap(),
      rejected = component.parameters
        .filter { it.kind == ParameterKind.UNSUPPORTED }
        .associate { it.name to (it.rejection ?: "unsupported") },
    )
  },
)

fun Dictionary.encode(): String = json.encodeToString(Dictionary.serializer(), this)

/**
 * Emits the guest stubs.
 *
 * Note what the emitted code does *not* do for a parameter whose default the host must resolve:
 * it does not send one. Absence is the "use host default" sentinel, and it is the only correct
 * encoding for a default the guest cannot evaluate — a `@Composable` default has no value until
 * it is composed, on the host, in context. Emitting a guest-computed stand-in would be a silent
 * theming bug on every screen.
 */
fun emitGuestStubs(packageName: String, dictionary: Dictionary, components: List<ParsedComponent>): String =
  buildString {
    appendLine("// Generated by dogwood-codegen. Do not edit.")
    appendLine("//")
    appendLine("// Segment '${dictionary.segmentName}' (id ${dictionary.segmentId}), version ${dictionary.version}.")
    appendLine("package $packageName")
    appendLine()
    appendLine("import androidx.compose.runtime.Composable")
    appendLine("import androidx.compose.runtime.ComposeNode")
    appendLine("import kotlinx.serialization.json.JsonPrimitive")
    appendLine()

    for (component in components.filter { it.isBindable }) {
      val entry = dictionary.components.first { it.name == component.name }
      appendLine("@Composable")
      append("fun ${component.name}(")
      appendLine()
      for (parameter in component.parameters) {
        val default = when {
          parameter.kind == ParameterKind.MODIFIER -> " = DogwoodModifier.Empty"
          parameter.defaultIsHostResolved -> " = null"
          parameter.hasDefault -> " = ${parameter.defaultExpression}"
          else -> ""
        }
        val type = if (parameter.defaultIsHostResolved && !parameter.type.endsWith("?")) {
          "${parameter.type}?"
        } else {
          parameter.type
        }
        appendLine("  ${parameter.name}: $type$default,")
      }
      appendLine(") {")
      appendLine("  ComposeNode<WidgetNode, DogwoodApplier>(")
      appendLine("    factory = { newWidget(widgetTag(${dictionary.segmentId}, ${entry.localTag})) },")
      appendLine("    update = {")
      for (parameter in component.values) {
        val tag = entry.properties.getValue(parameter.name)
        if (parameter.defaultIsHostResolved) {
          // Absence is the sentinel: send nothing, and the host resolves its own default.
          appendLine("      set(${parameter.name}) { if (it != null) recording.recorder.property(id, PropertyTag($tag), JsonPrimitive(it)) }")
        } else {
          appendLine("      set(${parameter.name}) { recording.recorder.property(id, PropertyTag($tag), JsonPrimitive(it)) }")
        }
      }
      component.modifier?.let {
        appendLine("      set(${it.name}) { if (it.elements.isNotEmpty()) recording.recorder.modifiers(id, it.elements) }")
      }
      for (parameter in component.events) {
        val tag = entry.events.getValue(parameter.name)
        appendLine("      set(${parameter.name}) { handler -> recording.lambdas.set(id, EventTag($tag)) { handler() } }")
      }
      appendLine("    },")
      if (component.slots.isNotEmpty()) {
        val slot = component.slots.first()
        val tag = entry.slots.getValue(slot.name)
        appendLine("    content = { Children(ChildrenTag($tag), ${slot.name}) },")
      }
      appendLine("  )")
      appendLine("}")
      appendLine()
    }
  }

/** A human-readable report of what the rule declined to bind, and why. */
fun emitAuditReport(components: List<ParsedComponent>): String = buildString {
  appendLine("| Component | Verdict | Reason |")
  appendLine("| --- | --- | --- |")
  for (component in components) {
    if (component.isBindable) {
      appendLine("| `${component.name}` | bindable | — |")
    } else {
      val reasons = component.parameters
        .filter { it.kind == ParameterKind.UNSUPPORTED }
        .joinToString("; ") { "`${it.name}`: ${it.rejection}" }
      appendLine("| `${component.name}` | **rejected** | $reasons |")
    }
  }
}
