/*
 * Project Dogwood -- the emitters.
 *
 * Four artifacts from one parsed model. Two are here; the value-type stand-ins and the host
 * bindings share the same shape and are noted where they are not yet built.
 *
 * Tag assignment is the load-bearing part. Tags are assigned by declaration order and never
 * renumbered, because the protocol's evolution rule is additive: a component that gains an
 * optional parameter appends a tag, and a client one dictionary version behind keeps rendering
 * everything it already knew. Sorting the components, or numbering by anything derived from the
 * signature, would silently re-map tags on an unrelated edit.
 */
package dev.dogwood.codegen

import kotlinx.serialization.json.Json

private val json = Json { prettyPrint = true }

/**
 * Builds the dictionary. Declaration order in, stable tags out.
 *
 * @param reservedLocalTags tags in this segment that hand-written bindings already answer to. The
 *   generator allocates around them; see [Dictionary.reservedLocalTags] for why that is not
 *   optional.
 */
fun buildDictionary(
  segmentName: String,
  segmentId: Int,
  version: Int,
  components: List<ParsedComponent>,
  reservedLocalTags: Set<Int> = emptySet(),
): Dictionary {
  val allocated = ArrayList<Int>(components.size)
  var next = 1
  repeat(components.size) {
    while (next in reservedLocalTags) next++
    allocated += next
    next++
  }
  return Dictionary(
  segmentName = segmentName,
  segmentId = segmentId,
  version = version,
  reservedLocalTags = reservedLocalTags.sorted(),
  components = components.mapIndexed { index, component ->
    DictionaryEntry(
      name = component.name,
      localTag = allocated[index],
      properties = component.values.mapIndexed { i, p -> p.name to i + 1 }.toMap(),
      slots = component.slots.mapIndexed { i, p -> p.name to i + 1 }.toMap(),
      events = component.events.mapIndexed { i, p -> p.name to i + 1 }.toMap(),
      rejected = component.parameters
        .filter { it.kind == ParameterKind.UNSUPPORTED }
        .associate { it.name to (it.rejection ?: "unsupported") },
    )
  },
  )
}

fun Dictionary.encode(): String = json.encodeToString(Dictionary.serializer(), this)

/**
 * Emits the guest stubs.
 *
 * Note what the emitted code does *not* do for a parameter whose default the host must resolve:
 * it does not send one. Absence is the "use host default" sentinel, and it is the only correct
 * encoding for a default the guest cannot evaluate — a `@Composable` default has no value until
 * it is composed, on the host, in context. Emitting a guest-computed stand-in would be a silent
 * theming bug on every screen.
 */
fun emitGuestStubs(packageName: String, dictionary: Dictionary, components: List<ParsedComponent>): String =
  buildString {
    appendLine("// Generated by dogwood-codegen. Do not edit.")
    appendLine("//")
    appendLine("// Segment '${dictionary.segmentName}' (id ${dictionary.segmentId}), version ${dictionary.version}.")
    appendLine("package $packageName")
    appendLine()
    appendLine("import androidx.compose.runtime.Composable")
    appendLine("import androidx.compose.runtime.ComposeNode")
    appendLine("import dev.dogwood.protocol.ChildrenTag")
    appendLine("import dev.dogwood.protocol.EventTag")
    appendLine("import dev.dogwood.protocol.PropertyTag")
    appendLine("import dev.dogwood.protocol.widgetTag")
    appendLine("import kotlinx.serialization.json.JsonPrimitive")
    appendLine("import kotlinx.serialization.json.booleanOrNull")
    appendLine("import kotlinx.serialization.json.floatOrNull")
    appendLine("import kotlinx.serialization.json.intOrNull")
    appendLine("import kotlinx.serialization.json.jsonPrimitive")
    appendLine()

    for (component in components.filter { it.isBindable }) {
      val entry = dictionary.components.first { it.name == component.name }
      appendLine("@Composable")
      append("fun ${component.name}(")
      appendLine()
      for (parameter in component.parameters) {
        val default = when {
          parameter.kind == ParameterKind.MODIFIER -> " = DogwoodModifier.Empty"
          parameter.defaultIsHostResolved -> " = null"
          parameter.hasDefault -> " = ${parameter.defaultExpression}"
          else -> ""
        }
        val type = if (parameter.defaultIsHostResolved && !parameter.type.endsWith("?")) {
          "${parameter.type}?"
        } else {
          parameter.type
        }
        appendLine("  ${parameter.name}: $type$default,")
      }
      appendLine(") {")
      appendLine("  ComposeNode<WidgetNode, DogwoodApplier>(")
      appendLine("    factory = { newWidget(widgetTag(${dictionary.segmentId}, ${entry.localTag})) },")
      appendLine("    update = {")
      for (parameter in component.values) {
        val tag = entry.properties.getValue(parameter.name)
        if (parameter.defaultIsHostResolved || parameter.type.endsWith("?")) {
          // Absence is the sentinel: an unset optional parameter sends nothing at all, and the
          // host resolves its own default. Sending an explicit null instead would put the word
          // "null" on the wire and, given a careless reader, on the screen.
          appendLine("      set(${parameter.name}) { if (it != null) recording.recorder.property(id, PropertyTag($tag), JsonPrimitive(it)) }")
        } else {
          appendLine("      set(${parameter.name}) { recording.recorder.property(id, PropertyTag($tag), JsonPrimitive(it)) }")
        }
      }
      component.modifier?.let {
        appendLine("      set(${it.name}) { if (it.elements.isNotEmpty()) recording.recorder.modifiers(id, it.elements) }")
        // `reconcile`, not `set`: it runs on every update rather than only when the chain
        // changes. A completion callback captured where the chain last *changed* would go stale,
        // which is the same defect the viewport reporter had.
        appendLine("      reconcile { applyModifier(id, ${it.name}) }")
      }
      for (parameter in component.events) {
        val tag = entry.events.getValue(parameter.name)
        appendLine("      set(${parameter.name}) { handler -> recording.lambdas.set(id, EventTag($tag)) ${guestEventBody(parameter)} }")
      }
      appendLine("    },")
      if (component.slots.isNotEmpty()) {
        val slot = component.slots.first()
        val tag = entry.slots.getValue(slot.name)
        appendLine("    content = { Children(ChildrenTag($tag), ${slot.name}) },")
      }
      appendLine("  )")
      appendLine("}")
      appendLine()
    }
  }

/** A human-readable report of what the rule declined to bind, and why. */
fun emitAuditReport(components: List<ParsedComponent>): String = buildString {
  appendLine("| Component | Verdict | Reason |")
  appendLine("| --- | --- | --- |")
  for (component in components) {
    if (component.isBindable) {
      appendLine("| `${component.name}` | bindable | — |")
    } else {
      val reasons = component.parameters
        .filter { it.kind == ParameterKind.UNSUPPORTED }
        .joinToString("; ") { "`${it.name}`: ${it.rejection}" }
      appendLine("| `${component.name}` | **rejected** | $reasons |")
    }
  }
}

/**
 * Emits the host binding layer.
 *
 * The generator emits the **bridge**, not the widget. A binding unpacks a node's properties,
 * slots and events and calls an implementation a human wrote; it does not decide what a badge
 * looks like. That split is the whole architecture: the part that grows without bound as a design
 * system grows is generated, and the part that requires taste is not.
 *
 * Redwood draws the same line, and it is why "the registry stops being a treadmill; it does not
 * stop existing".
 */
fun emitHostBindings(
  packageName: String,
  implementationPackage: String,
  dictionary: Dictionary,
  components: List<ParsedComponent>,
): String = buildString {
  val bindable = components.filter { it.isBindable }
  appendLine("// Generated by dogwood-codegen. Do not edit.")
  appendLine("//")
  appendLine("// Segment '${dictionary.segmentName}' (id ${dictionary.segmentId}), version ${dictionary.version}.")
  appendLine("package $packageName")
  appendLine()
  appendLine("import androidx.compose.runtime.Composable")
  appendLine("import dev.dogwood.protocol.EventTag")
  appendLine("import dev.dogwood.protocol.widgetTag")
  appendLine("import kotlinx.serialization.json.JsonPrimitive")
  appendLine()
  appendLine("/** Local tags this segment binds, for the dictionary check and for skew reporting. */")
  appendLine("val ${dictionary.segmentName.replaceFirstChar { it.uppercase() }}Tags: Set<Int> = setOf(")
  for (entry in dictionary.components.filter { e -> bindable.any { it.name == e.name } }) {
    appendLine("  widgetTag(${dictionary.segmentId}, ${entry.localTag}).value,")
  }
  appendLine(")")
  appendLine()
  appendLine("/**")
  appendLine(" * Dispatches one node to its implementation. Returns false when the tag is not ours,")
  appendLine(" * so a caller can try another segment before falling back to a placeholder.")
  appendLine(" *")
  appendLine(" * The tag is checked **before** the modifier chain is built, and that ordering is")
  appendLine(" * load-bearing rather than tidy. Building it first meant every node from another")
  appendLine(" * segment built its chain twice -- once here, once in the caller after this returned")
  appendLine(" * false. That was merely wasteful until modifier arguments could be animated, at which")
  appendLine(" * point it became two animations and two completion events for one declared target.")
  appendLine(" */")
  appendLine("@Composable")
  appendLine("fun bind${dictionary.segmentName.replaceFirstChar { it.uppercase() }}(")
  appendLine("  node: WidgetView,")
  appendLine("  scope: LayoutScope,")
  appendLine("  events: EventSink,")
  appendLine("): Boolean {")
  appendLine("  if (node.tag.value !in ${dictionary.segmentName.replaceFirstChar { it.uppercase() }}Tags) return false")
  appendLine("  val modifier = node.composeModifier(scope, events)")
  appendLine("  when (node.tag.value) {")

  for (component in bindable) {
    val entry = dictionary.components.first { it.name == component.name }
    appendLine("    widgetTag(${dictionary.segmentId}, ${entry.localTag}).value ->")
    appendLine("      $implementationPackage.${component.name}Impl(")
    for (parameter in component.values) {
      val tag = entry.properties.getValue(parameter.name)
      appendLine("        ${parameter.name} = ${reader(parameter, tag)},")
    }
    component.modifier?.let { appendLine("        ${it.name} = modifier,") }
    for (parameter in component.events) {
      val tag = entry.events.getValue(parameter.name)
      appendLine("        ${parameter.name} = ${eventLambda(parameter, tag)},")
    }
    for (parameter in component.slots) {
      val tag = entry.slots.getValue(parameter.name)
      appendLine("        ${parameter.name} = { RenderChildren(node, $tag, scope, events) },")
    }
    appendLine("      )")
  }

  appendLine("    else -> return false")
  appendLine("  }")
  appendLine("  return true")
  appendLine("}")
}

/**
 * The guest side of an event's arguments.
 *
 * The slot table stores a lambda taking the event's argument list, so a handler declared
 * `(Boolean) -> Unit` has to be called with that boolean decoded out of the list. Emitting
 * `{ handler() }` for every event compiles only for the zero-argument case, which is why the
 * first event with an argument found this.
 */
private fun guestEventBody(parameter: ParsedParameter): String {
  val arguments = parameter.type
    .substringAfter("(").substringBefore(")")
    .split(",").map { it.trim() }.filter { it.isNotEmpty() }
  if (arguments.isEmpty()) return "{ handler() }"
  val decoded = arguments.mapIndexed { index, type ->
    when (type.removeSuffix("?")) {
      "Boolean" -> "args[$index].jsonPrimitive.booleanOrNull ?: false"
      "Int" -> "args[$index].jsonPrimitive.intOrNull ?: 0"
      "Float" -> "args[$index].jsonPrimitive.floatOrNull ?: 0f"
      else -> "args[$index].jsonPrimitive.content"
    }
  }
  return "{ args -> handler(${decoded.joinToString(", ")}) }"
}

/**
 * The lambda a binding hands to an implementation.
 *
 * Its shape has to match the declared one: an event declared `(Boolean) -> Unit` must be handed a
 * one-argument lambda, and that argument has to reach the guest. `Event` has carried an argument
 * list since ADR-004's first draft, and this is where the generator uses it.
 */
private fun eventLambda(parameter: ParsedParameter, tag: Int): String {
  val arguments = parameter.type
    .substringAfter("(").substringBefore(")")
    .split(",").map { it.trim() }.filter { it.isNotEmpty() }
  if (arguments.isEmpty()) return "{ events.send(node, EventTag($tag)) }"
  val names = arguments.indices.map { "a$it" }
  val encoded = names.joinToString(", ") { "JsonPrimitive($it)" }
  return "{ ${names.joinToString(", ")} -> events.send(node, EventTag($tag), listOf($encoded)) }"
}

/**
 * How a binding reads one property.
 *
 * A host-resolved default is read as null and the implementation supplies its own, which is the
 * receiving half of absence-as-sentinel: the guest sent nothing precisely so the host could
 * decide, and a binding that substituted a value here would throw that away.
 */
private fun reader(parameter: ParsedParameter, tag: Int): String {
  val nullable = parameter.defaultIsHostResolved || parameter.type.endsWith("?")
  // The surface's own default is carried through. Substituting a plausible-looking zero here
  // would make the generated binding disagree with the declaration it was generated from, which
  // is the one failure the whole approach is supposed to make impossible.
  val fallback = parameter.defaultExpression?.takeIf { !parameter.defaultIsHostResolved }
  return when (parameter.type.removeSuffix("?")) {
    "String" -> if (nullable) "node.stringOrNull($tag)" else "node.string($tag, ${fallback ?: "\"\""})"
    "Int" -> if (nullable) "node.intOrNull($tag)" else "node.int($tag, ${fallback ?: "0"})"
    "Float" -> if (nullable) "node.floatOrNull($tag)" else "node.float($tag, ${fallback ?: "0f"})"
    "Boolean" -> if (nullable) "node.booleanOrNull($tag)" else "node.boolean($tag, ${fallback ?: "false"})"
    else -> "node.property($tag)"
  }
}
