/*
 * Project Dogwood -- the generator's command-line entry point.
 *
 * A standalone tool rather than a Kotlin Symbol Processing processor, per Layer 5 ADR-002:
 * neither Zipline nor Redwood uses symbol processing for its bridge, and the generator must run
 * over sources it does not compile.
 */
package dev.dogwood.codegen

import java.io.File

fun main(args: Array<String>) {
  val options = args.toList().chunked(2).associate { it[0].removePrefix("--") to it[1] }
  fun required(name: String) = options[name] ?: error("missing --$name")

  val sourceDir = File(required("source"))
  val segmentName = required("segment")
  val segmentId = required("segment-id").toInt()
  val version = required("version").toInt()
  val guestOut = File(required("guest-out"))
  val hostOut = File(required("host-out"))
  val dictionaryOut = File(required("dictionary-out"))
  // Optional, and only Dogwood's own build passes it. It writes `DogwoodSegments`, the vector of
  // segment names and versions that every host reads — including the Web one, which cannot see
  // `dogwood-host` at all. A product segment has no business writing that file: it would overwrite
  // the engine's constants with its own, which is not a compile error and is not a wrong number
  // either. It is the engine's segments simply disappearing.
  val wireOut = options["wire-out"]?.let(::File)
  val guestPackage = required("guest-package")
  val hostPackage = required("host-package")
  val implementationPackage = required("impl-package")

  val sources = sourceDir.walkTopDown().filter { it.extension == "kt" }.toList()
  require(sources.isNotEmpty()) { "no Kotlin sources under $sourceDir" }

  // Local tags in this segment that hand-written bindings already own. Comma separated.
  val reserved = options["reserved"]
    ?.split(",")
    ?.mapNotNull { it.trim().toIntOrNull() }
    ?.toSet()
    .orEmpty()

  // What a guest calls this segment. Defaults to the Kotlin-identifier name, because for a
  // product surface the two are usually the same; Dogwood's own design system is dotted on the
  // wire and camel-cased in code, which is why this is an option rather than a convention.
  val wireName = options["wire-name"] ?: segmentName

  val components = SurfaceParser().parseFiles(sources)
  val dictionary =
    buildDictionary(segmentName, segmentId, version, components, reserved, wireName)

  /*
   * The segment-version vector, emitted where every platform can read it.
   *
   * It used to be assembled by hand in `Bindings.kt`, which lives in `dogwood-host` and cannot
   * compile for WebAssembly -- so the web host declared its own copy of the same numbers, and
   * nothing compared them. That is the drift this project has now fixed three times: a number that
   * means one thing on one side of a boundary and something else on the other does not fail, it
   * quietly misinforms. Generating it once removes the second copy rather than policing it.
   */
  wireOut?.parentFile?.mkdirs()
  wireOut?.writeText(
    buildString {
      appendLine("// GENERATED by dogwood-codegen. Do not edit.")
      appendLine("package dev.dogwood.protocol")
      appendLine()
      appendLine("/**")
      appendLine(" * Dictionary segment names and the versions this build implements.")
      appendLine(" *")
      appendLine(" * Emitted into the transport-free module so that every host -- Android, iOS,")
      appendLine(" * desktop and Web -- reads the same numbers instead of restating them. A host")
      appendLine(" * advertises the subset it actually implements; the Web host, for instance, binds")
      appendLine(" * the layout segment and not the design system, and says so honestly by omission.")
      appendLine(" */")
      appendLine("object DogwoodSegments {")
      appendLine("  const val LAYOUT: String = \"androidx.layout\"")
      appendLine("  const val LAYOUT_VERSION: Int = 1")
      appendLine()
      appendLine("  const val DESIGN_SYSTEM: String = \"${dictionary.wireName}\"")
      appendLine("  const val DESIGN_SYSTEM_VERSION: Int = ${dictionary.version}")
      appendLine("}")
    },
  )

  // Layer 1's build-time check. A renumbered tag does not fail to render; it renders the wrong
  // widget on a client one dictionary version behind, so this fails the build rather than the
  // screen.
  options["lock"]?.let { lockPath ->
    when (val result = checkAgainstLock(dictionary, File(lockPath))) {
      is LockResult.Violated -> error(
        buildString {
          appendLine("dictionary lock violated; tags are permanent:")
          for (problem in result.problems) appendLine("  - " + problem)
          appendLine("Append to the surface instead of reordering or removing.")
        },
      )
      is LockResult.Updated -> println("dogwood-codegen: dictionary lock updated, added ${result.added}")
      LockResult.Unchanged -> Unit
    }
  }

  guestOut.parentFile.mkdirs()
  hostOut.parentFile.mkdirs()
  dictionaryOut.parentFile.mkdirs()
  guestOut.writeText(emitGuestStubs(guestPackage, dictionary, components))
  hostOut.writeText(emitHostBindings(hostPackage, implementationPackage, dictionary, components))
  dictionaryOut.writeText(dictionary.encode())

  val rejected = components.filterNot { it.isBindable }
  println("dogwood-codegen: ${components.size} composables, ${components.size - rejected.size} bound, ${rejected.size} rejected")
  for (component in rejected) {
    for (parameter in component.parameters.filter { it.kind == ParameterKind.UNSUPPORTED }) {
      println("  rejected ${component.name}.${parameter.name}: ${parameter.rejection}")
    }
  }
}
