/*
 * Project Dogwood -- the coverage report: what generator v2 can bind of the pinned surface.
 *
 * This is the number every document quotes from now on, and it is emitted by a Gradle task rather
 * than typed, for the reason ADR-005 corrected the previous two measurements: a figure nobody can
 * regenerate is a figure nobody can check. The three buckets are ADR-005's -- generable, bespoke,
 * unreachable -- so the two measurements can be read side by side, with a fourth for the thing a
 * library has that a surface does not: a component the rule accepts but whose generated binding
 * does not compile on the host, because a default expression names something not public. Those
 * live in `exclusions.txt`, with the compiler's own reason.
 */
package dev.dogwood.codegen.v2

import java.io.File
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
data class CoverageRow(
  val module: String,
  val file: String,
  val name: String,
  val dictionaryName: String,
  val bound: Boolean,
  val bucket: String,
  val reason: String?,
  val settable: List<String>,
  val hostDefaultOnly: List<String>,
  val experimental: Boolean,
)

@Serializable
data class CoverageTotals(
  val composables: Int,
  val bound: Int,
  val generableExcluded: Int,
  val bespoke: Int,
  val unreachable: Int,
  val deprecated: Int,
  val settableParameters: Int,
  val hostDefaultOnlyParameters: Int,
)

@Serializable
data class CoverageReport(val modules: Map<String, CoverageTotals>, val overall: CoverageTotals, val rows: List<CoverageRow>)

/** `dictionaryName<TAB>reason` per line; `#` comments. Absent file means nothing excluded. */
fun readExclusions(file: File?): Map<String, String> {
  if (file == null || !file.exists()) return emptyMap()
  return file.readLines()
    .map { it.trim() }
    .filter { it.isNotEmpty() && !it.startsWith("#") }
    .associate { line -> line.substringBefore('\t').trim() to line.substringAfter('\t', "no reason recorded").trim() }
}

/** ADR-005's bucket for a reason, so the two measurements compare. */
fun bucketOf(reason: String?): String = when {
  reason == null -> "generable"
  reason.startsWith("deprecated") -> "deprecated"
  reason.startsWith("controlled text input") -> "bespoke"
  reason.startsWith("guest signature identical") -> "generable-excluded"
  reason.contains("default names internal") || reason.startsWith("requires an opt-in the library keeps internal") -> "generable-excluded"
  reason.contains("invoked inside a frame") || reason.contains("generic") ||
    reason.contains("extension on") || reason.contains("vararg") || reason.contains("slot receives") -> "unreachable"
  else -> "bespoke"
}

fun buildCoverage(
  surfaces: List<Pair<String, List<ClassifiedComposable>>>,
  exclusions: Map<String, String>,
): CoverageReport {
  val rows = surfaces.flatMap { (module, composables) ->
    composables.map { c ->
      val excluded = exclusions[c.dictionaryName]
      val reason = c.unbindableReason ?: excluded?.let { "excluded: $it" }
      val bucket = if (c.unbindableReason == null && excluded != null) "generable-excluded" else bucketOf(c.unbindableReason)
      CoverageRow(
        module = module, file = c.source.file, name = c.source.name, dictionaryName = c.dictionaryName,
        bound = reason == null, bucket = bucket, reason = reason,
        settable = c.settable.map { it.parameter.name },
        hostDefaultOnly = c.hostDefaultOnly.map { it.parameter.name },
        experimental = c.source.optIns.isNotEmpty(),
      )
    }
  }
  fun totals(of: List<CoverageRow>) = CoverageTotals(
    composables = of.size,
    bound = of.count { it.bound },
    generableExcluded = of.count { it.bucket == "generable-excluded" },
    bespoke = of.count { it.bucket == "bespoke" },
    unreachable = of.count { it.bucket == "unreachable" },
    deprecated = of.count { it.bucket == "deprecated" },
    settableParameters = of.filter { it.bound }.sumOf { it.settable.size },
    hostDefaultOnlyParameters = of.filter { it.bound }.sumOf { it.hostDefaultOnly.size },
  )
  return CoverageReport(
    modules = rows.groupBy { it.module }.toSortedMap().mapValues { totals(it.value) },
    overall = totals(rows),
    rows = rows,
  )
}

fun CoverageReport.toMarkdown(versions: Map<String, String>): String = buildString {
  appendLine("<!-- GENERATED by dogwood-codegen's generateComposeCoverage task. Do not edit. -->")
  appendLine()
  appendLine("# Generator v2 coverage of the pinned Compose surface")
  appendLine()
  appendLine("What the v2 bindability rule (plans/generator-v2.md, D-E) makes of every public,")
  appendLine("uppercase `@Composable` in the `commonMain` sources of the artifacts the host resolves.")
  appendLine("**Bound** means a guest stub and a host binding are generated and the binding compiles;")
  appendLine("**generable, excluded** means the rule accepts it and the host compiler did not, with")
  appendLine("the reason in `engine/dogwood-material3/exclusions.txt`; **bespoke** and **unreachable** are")
  appendLine("ADR-005's buckets. *Settable* counts parameters a payload may set on bound components;")
  appendLine("*host-default* counts parameters a payload cannot set, which the host passes the library's")
  appendLine("own default for. Function coverage overstates parameter coverage, and both are here.")
  appendLine()
  appendLine("| Module | Version | Composables | Bound | Generable, excluded | Bespoke | Unreachable | Deprecated | Settable params | Host-default params |")
  appendLine("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|")
  for ((module, t) in modules) {
    appendLine("| `$module` | ${versions[module] ?: ""} | ${t.composables} | **${t.bound}** | ${t.generableExcluded} | ${t.bespoke} | ${t.unreachable} | ${t.deprecated} | ${t.settableParameters} | ${t.hostDefaultOnlyParameters} |")
  }
  val o = overall
  appendLine("| **all** | | **${o.composables}** | **${o.bound}** | ${o.generableExcluded} | ${o.bespoke} | ${o.unreachable} | ${o.deprecated} | ${o.settableParameters} | ${o.hostDefaultOnlyParameters} |")
  appendLine()
  val pct = if (o.composables == 0) 0.0 else 100.0 * o.bound / o.composables
  appendLine("**${o.bound} of ${o.composables} bound (${"%.1f".format(pct)}%).** Affordance rule for a library tier: a")
  appendLine("`Boolean` parameter named `enabled`, `checked`, `selected` or `readOnly` withholds the widget on")
  appendLine("unreadable skew, exactly as `@Affordance` does on a product surface.")
  appendLine()
  for ((module, rowsOfModule) in rows.groupBy { it.module }.toSortedMap()) {
    appendLine("## `$module`")
    appendLine()
    appendLine("| Component | Bound | Settable | Host default only | Why not |")
    appendLine("|---|:---:|---|---|---|")
    for (r in rowsOfModule.sortedWith(compareBy({ it.file }, { it.dictionaryName }))) {
      val flag = if (r.experimental) " ⚠" else ""
      appendLine(
        "| `${r.dictionaryName}`$flag | ${if (r.bound) "✅" else ""} | ${r.settable.joinToString(", ")} | ${r.hostDefaultOnly.joinToString(", ")} | ${r.reason ?: ""} |",
      )
    }
    appendLine()
  }
  appendLine("⚠ marks a component behind an experimental opt-in in the library; it may change under a host.")
}

fun CoverageReport.toJson(): String = Json { prettyPrint = true }.encodeToString(CoverageReport.serializer(), this)
