/*
 * Umbra -- a whole product consuming Dogwood from outside the repository.
 *
 * This is a **separate Gradle build**. It has no `includeBuild`, no project dependency and no path
 * into `engine/`; everything it uses is resolved from a repository, which is the only way to find
 * out whether Dogwood is consumable rather than merely modular.
 *
 * It grew from one module to three when the adoption audit (`plans/adoption-audit.md` A2) observed
 * that the original Umbra proved the HOST half only -- a design system that compiles -- while no
 * build outside the repository had ever produced a *payload*. A product is both halves plus an
 * application, so Umbra is now all three:
 *
 *   :design  the product's own component surface -- host bindings generated by the Dogwood plugin
 *   :guest   the payload: a screen in Kotlin, compiled to JavaScript, signed, served over HTTP
 *   :app     a desktop host application that fetches, verifies and renders that payload
 *
 * `mavenLocal()` is what a developer has before anything is published anywhere. A real product
 * would point at the repository the artifacts are actually deployed to; that is a deployment
 * decision and is tracked in `OPEN-DECISIONS.md` rather than decided here.
 */
pluginManagement {
  repositories {
    mavenLocal()
    gradlePluginPortal()
    mavenCentral()
    // The Zipline Gradle plugin's own classpath reaches androidx artifacts, which live on
    // Google's Maven and nowhere else. An adopter writes this line too.
    google()
  }
}

dependencyResolutionManagement {
  repositories {
    mavenLocal()
    mavenCentral()
    google()
  }
}

rootProject.name = "umbra"

// `:android`, `:web` and `:ios` are compile probes rather than product modules -- see each build
// file for what it proves and what it does not. `:android` exists because for as long as `:app`, a
// desktop application, was the only consumer here, the flagship platform's artifact path was
// exercised by nothing and was broken; `:web` and `:ios` exist so the other two shipping platforms
// are not in that position. `:web-guest` is the payload as a Web Worker builds it.
include(":design", ":guest", ":app", ":android", ":web", ":web-guest", ":ios")
