/*
 * Umbra's payload, as a Web Worker builds it.
 *
 * The same screen `:guest` ships -- literally the same source directory -- with a different
 * transport underneath: no Zipline plugin, no signed manifest, and a `main` that hands the guest to
 * `runInWorker` from `dogwood-compose`. That function is the four hundred lines of `postMessage`
 * plumbing a product used to have to copy from a sample, and this module is what asserts a product
 * no longer has to: the transport resolves from a published artifact and the entry point is the
 * entry-point list plus one call.
 *
 * **What this proves, and what it does not.** That a payload outside the engine compiles for a
 * Worker against published artifacts and that webpack emits a bundle a page could load. It is not
 * loaded here; the Worker path is rendered and graded by the engine's own web conformance drill,
 * against the engine's own guest. What that drill could not cover was a *product's* guest reaching
 * the Worker transport at all, which until 2026-09-13 meant copying a sample.
 */
plugins {
  kotlin("multiplatform")
  kotlin("plugin.serialization")
  id("org.jetbrains.kotlin.plugin.compose")
}

kotlin {
  jvmToolchain(21)
  js(IR) {
    outputModuleName.set("umbra-web-guest")
    browser {
      commonWebpackConfig {
        outputFileName = "guest-kotlin.js"
        // A Worker script is loaded by `new Worker(url)`, not by a page, so webpack must not emit
        // anything that assumes a `document`. `web` would inject a DOM-based chunk loader that
        // throws the moment the Worker starts.
        output?.globalObject = "self"
      }
    }
    binaries.executable()
  }
  sourceSets {
    jsMain {
      dependencies {
        // The guest runtime -- and, since the Worker bridge became a library, the transport too.
        implementation("dev.dogwood:dogwood-compose:0.1.0")
      }
      // Umbra's own components, generated by the Dogwood plugin in `:design` from Umbra's surface.
      kotlin.srcDir(project(":design").layout.buildDirectory.dir("generated/dogwood/umbraDesignSystem/guest"))
      // The screens, shared with `:guest`: one set of screens, two transports.
      kotlin.srcDir("../guest/screens/kotlin")
    }
  }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
  dependsOn(":design:generateUmbraDesignSystem")
}
